SRC_HC_OPTS        = -O -H64m
BuildFlavour       = perf
GhcStage1HcOpts    = -O
GhcStage2HcOpts    = -O2
GhcLibHcOpts       = -O2
GhcWithLlvmCodeGen = YES
BUILD_PROF_LIBS    = YES
SplitObjs          = NO
SplitSections      = YES
BUILD_MAN          = NO
BUILD_SPHINX_HTML  = YES
BUILD_SPHINX_PDF   = NO
HADDOCK_DOCS       = YES
EXTRA_HADDOCK_OPTS += --quickjump --hyperlinked-source
