V=0
BuildFlavour        = perf-llvm
BUILD_MAN           = NO
BUILD_SPHINX_HTML   = NO
BUILD_SPHINX_PDF    = NO
HADDOCK_DOCS        = NO
GhcWithLlvmCodeGen  = YES
INTEGER_LIBRARY     = integer-simple
SplitSections       = YES
