name: "`ghcup` image"

on:
  # FIXME: Remove this before merging!
  pull_request: { branches: [ "master" ] }
  push: { branches: [ "release" ] }

env:
  alpine_ver: "3.14"

jobs:
  build:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Check this repository out."
        uses: "actions/checkout@v2"

      - name: "Build `ghcup` image."
        id: "build-ghcup-image"
        run: |
          image=$(
            ./ghcup/builder.sh \
              -a "${{ env.alpine_ver }}" \
            | tail -n 1
          )
          echo "::set-output name=image::${image}"

      - name: "Push `ghcup` image to the GitHub Container Registry"
        id: "push-ghcup-to-ghcr"
        uses: "redhat-actions/push-to-registry@v2"
        with:
          image: "${{ steps.build-ghcup-image.outputs.image }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
          registry: "ghcr.io/${{ github.repository_owner }}"

      - name: "Print image URL."
        run: |
          echo "Image pushed to [ ${{ steps.push-ghcup-to-ghcr.outputs.registry-paths }} ]"
